name: clinixai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase Core and Auth
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.5.0
  firebase_messaging: ^16.2.0 # For the doctor alerts/FCM

  # Networking & State
  dio: ^5.4.0 # To talk to your FastAPI backend
  provider: ^6.1.1 # To manage user state (Patient vs Doctor)

  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  shared_preferences: ^2.5.5
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.0
  universal_html: ^2.3.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/finallogo.png
