// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhdp9hf3QoP3z6VQVJalHSLSbPhiBMrXg',
    appId: '1:109177663265:web:947ab33ae1279b9de11860',
    messagingSenderId: '109177663265',
    projectId: 'clinixai-9fd9a',
    authDomain: 'clinixai-9fd9a.firebaseapp.com',
    storageBucket: 'clinixai-9fd9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC74xWZtagDUAy6QNj_ieQpB2QNvmsjcMQ',
    appId: '1:109177663265:android:4ffce9933e935a4de11860',
    messagingSenderId: '109177663265',
    projectId: 'clinixai-9fd9a',
    storageBucket: 'clinixai-9fd9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ZVCEKWUl6-SFOqivmSK4Q2k8kHOsklk',
    appId: '1:109177663265:ios:efeee91ce63d61c9e11860',
    messagingSenderId: '109177663265',
    projectId: 'clinixai-9fd9a',
    storageBucket: 'clinixai-9fd9a.firebasestorage.app',
    iosBundleId: 'com.example.clinixai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ZVCEKWUl6-SFOqivmSK4Q2k8kHOsklk',
    appId: '1:109177663265:ios:efeee91ce63d61c9e11860',
    messagingSenderId: '109177663265',
    projectId: 'clinixai-9fd9a',
    storageBucket: 'clinixai-9fd9a.firebasestorage.app',
    iosBundleId: 'com.example.clinixai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhdp9hf3QoP3z6VQVJalHSLSbPhiBMrXg',
    appId: '1:109177663265:web:eafcef3a8b27edc3e11860',
    messagingSenderId: '109177663265',
    projectId: 'clinixai-9fd9a',
    authDomain: 'clinixai-9fd9a.firebaseapp.com',
    storageBucket: 'clinixai-9fd9a.firebasestorage.app',
  );
}
